export default {
  created_at: 'Fri Jan 22 19:58:16 +0000 2021',
  id: 1352707172396920800,
  id_str: '1352707172396920837',
  full_text: '@humancoders TL;DR',
  truncated: false,
  display_text_range: [13, 18],
  entities: {
    hashtags: [],
    symbols: [],
    user_mentions: [
      {
        screen_name: 'humancoders',
        name: 'Human Coders',
        id: 492462042,
        id_str: '492462042',
        indices: [0, 12],
      },
    ],
    urls: [],
  },
  source:
    "<a href='https://mobile.twitter.com' rel='nofollow'>Twitter Web App</a>",
  in_reply_to_status_id: 1352601919752073200,
  in_reply_to_status_id_str: '1352601919752073216',
  in_reply_to_user_id: 492462042,
  in_reply_to_user_id_str: '492462042',
  in_reply_to_screen_name: 'humancoders',
  user: {
    id: 879891577,
    id_str: '879891577',
    name: "Romain l'Ourson",
    screen_name: 'r_ourson',
    location: '',
    description: 'Maintainer of https://t.co/boZWfc29ah Graou !',
    url: 'https://t.co/boZWfc29ah',
    entities: {
      url: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [0, 23],
          },
        ],
      },
      description: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [14, 37],
          },
        ],
      },
    },
    protected: false,
    followers_count: 138,
    friends_count: 203,
    listed_count: 9,
    created_at: 'Sun Oct 14 11:13:07 +0000 2012',
    favourites_count: 127,
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    verified: false,
    statuses_count: 556,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: true,
    profile_background_color: '000000',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_banner_url:
      'https://pbs.twimg.com/profile_banners/879891577/1417039033',
    profile_link_color: 'ABB8C2',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    translator_type: 'none',
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 1,
  favorited: false,
  retweeted: false,
  lang: 'in',
};
